[project]
name = "journey"
version = "0.1.0"
description = "Read and write about your life"
readme = "README.md"
requires-python = ">=3.13"
dependencies = []

[dependency-groups]
dev = [
    "mkdocs>=1.5.0",
    "mkdocs-material[imaging]>=9.4.0",
]
